[build]
  publish = "public"
  command = "yarn build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "16.15.0"

[[edge_functions]]
  function = "hello"
  path = "/test"

[[edge_functions]]
  function = "demo1"
  path = "/demo1"

[[edge_functions]]
  function = "demo2"
  path = "/demo2"