name: Continuous Integration

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        npm ci --legacy-peer-deps
    - name: Lint
      run: |
        npm run lint
    - name: Deploy Staging
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm run arc deploy -- --staging